routes/web.php
<?php

use App\Http\Controllers\Admin\BasisPengetahuanController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DiagnosaController as AdminDiagnosaController;
use App\Http\Controllers\Admin\GejalaController;
use App\Http\Controllers\Admin\KategoriGejalaController;
use App\Http\Controllers\Admin\PenyakitController;
use App\Http\Controllers\Admin\SolusiController;
use App\Http\Controllers\Admin\SolusiPenyakitController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\User\DashboardController as UserDashboardController;
use App\Http\Controllers\User\DiagnosaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth', 'role:admin'], 'as' => 'admin.', 'prefix' => 'admin'], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('kategori-gejala', KategoriGejalaController::class)->except('show');
    Route::resource('gejala', GejalaController::class);
    Route::resource('penyakit', PenyakitController::class);
    Route::resource('solusi', SolusiController::class);

    Route::get('/penyakit/{penyakit}/solusi', [SolusiPenyakitController::class, 'edit'])->name('penyakit.solusi.edit');
    Route::put('/penyakit/{penyakit}/solusi', [SolusiPenyakitController::class, 'update'])->name('penyakit.solusi.update');

    Route::get('/basis-pengetahuan', [BasisPengetahuanController::class, 'index'])->name('basis-pengetahuan.index');
    Route::get('/basis-pengetahuan/{penyakit}/edit', [BasisPengetahuanController::class, 'edit'])->name('basis-pengetahuan.edit');
    Route::put('/basis-pengetahuan/{penyakit}', [BasisPengetahuanController::class, 'update'])->name('basis-pengetahuan.update');

    Route::resource('diagnosa', AdminDiagnosaController::class)->only(['index', 'show', 'destroy']);
    Route::resource('users', UserController::class)->only(['index', 'show', 'destroy']);
});

Route::group(['middleware' => ['auth', 'role:user'], 'as' => 'user.', 'prefix' => 'user'], function () {
    Route::get('/dashboard', [UserDashboardController::class, 'index'])->name('dashboard');

    Route::resource('diagnosa', DiagnosaController::class)->except(['edit', 'update']);
});

Route::group(['middleware' => ['auth'], 'as' => 'profile.', 'prefix' => 'profile'], function () {
    Route::get('/', [ProfileController::class, 'index'])->name('index');
    Route::put('/', [ProfileController::class, 'update'])->name('update');
    Route::delete('/delete-profile-picture', [ProfileController::class, 'deleteProfilePicture'])->name('delete-profile-picture');
});

require __DIR__ . '/auth.php';

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class User extends Authenticatable implements HasMedia
{
    use HasApiTokens, HasFactory, InteractsWithMedia, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    /**
     * Mendapatkan URL Foto Profil Admin
     * 
     * Mendapatkan url foto profil dari media yang terlampir ke model.
     * Jika tidak ada, dapatkan URL dari website ui-avatars.com melalui fungsi getAvatar()
     * 
     * @return string URL Foto Profil
     */
    public function getAvatar(): string
    {
        return isset($this->media[0]) ? $this->media[0]->getFullUrl() : getAvatar($this->name);
    }

    /**
     * Relasi one-to-many ke model Diagnosa
     * 
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function diagnosa(): HasMany
    {
        return $this->hasMany(Diagnosa::class, 'user_id', 'id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $data = User::withCount('diagnosa')->where('role', 'user')->get();

        return view('admin.users.index', compact('data'));
    }

    /**
     * Display the specified resource.
     */
    public function show(User $user)
    {
        $user->loadCount('diagnosa');
        $user->load('diagnosa.penyakit');

        return view('admin.users.show', compact('user'));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()
            ->route('admin.users.index')
            ->withSuccess('Berhasil menghapus data user');
    }
}

app/Http/Controllers/User/DashboardController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Diagnosa;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        $riwayatDiagnosa = Diagnosa::with('penyakit')->where('user_id', auth()->user()->id)->take(5)->get();
        
        return view('user.dashboard', compact('riwayatDiagnosa'));
    }
}

app/Http/Controllers/User/DiagnosaController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Diagnosa;
use App\Models\Gejala;
use App\Services\DiagnosaService;
use Illuminate\Http\Request;

class DiagnosaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $data = Diagnosa::with('penyakit')->where('user_id', auth()->user()->id)->latest()->paginate();

        return view('user.diagnosa.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $gejala = Gejala::with('kategori')->orderBy('kode')->get();

        $gejala = $gejala->groupBy('id_kategori')->map(function ($item, $key) {
            if ($key == null) {
                $key = 'Lainnya';
            } else {
                $key = $item->first()->kategori->nama;
            }

            return [
                'kategori' => $key,
                'data' => $item,
            ];
        })->sortByDesc(function ($item) {
            return $item['kategori'] === 'Lainnya' ? PHP_INT_MAX : $item['kategori'];
        });

        return view('user.diagnosa.create', compact('gejala'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'gejala' => 'required|array',
        ]);

        $diagnosa = auth()->user()->diagnosa()->create();
        $diagnosa->gejala()->attach($request->gejala);

        $diagnosaService = new DiagnosaService($diagnosa);
        $hasilPerhitungan = $diagnosaService->penyakitTertinggi();

        $diagnosa->update([
            'id_penyakit' => $hasilPerhitungan['penyakit']['id'],
            'persentase' => $hasilPerhitungan['cf_kombinasi']['persentase'],
        ]);

        return redirect()
            ->route('user.diagnosa.show', $diagnosa->id)
            ->withSuccess('Berhasil melakukan diagnosa');
    }

    /**
     * Display the specified resource.
     */
    public function show(Diagnosa $diagnosa)
    {
        return view('user.diagnosa.show', compact('diagnosa'));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Diagnosa $diagnosa)
    {
        $diagnosa->delete();

        return redirect()
            ->route('user.diagnosa.index')
            ->withSuccess('Berhasil menghapus riwayat diagnosa');
    }
}

resources/views/admin/users/index.blade.php
@extends('layouts.metronic')
@section('title', 'Kelola Data User')

@section('breadcrumb')
    <div class="toolbar py-5 pb-lg-15" id="kt_toolbar">
        <!--begin::Container-->
        <div id="kt_toolbar_container" class=" container-xxl  d-flex flex-stack flex-wrap">
            <!--begin::Page title-->
            <div class="page-title d-flex flex-column me-3">
                <!--begin::Title-->
                <h1 class="d-flex text-white fw-bold my-1 fs-3">
                    Kelola Data User
                </h1>
                <!--end::Title-->
                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-1">
                    <!--begin::Item-->
                    <li class="breadcrumb-item text-white opacity-75">
                        <a href="{{ route('admin.dashboard') }}" class="text-white text-hover-primary">
                            Dashboard </a>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li class="breadcrumb-item">
                        <span class="bullet bg-white opacity-75 w-5px h-2px"></span>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li class="breadcrumb-item text-white opacity-75">
                        Kelola Data User
                    </li>
                    <!--end::Item-->
                </ul>
                <!--end::Breadcrumb-->
            </div>
            <!--end::Page title-->
        </div>
        <!--end::Container-->
    </div>
@endsection

@section('content')
    <div class="content flex-row-fluid" id="kt_content">
        <!--begin::Row-->
        <div class="row g-5 g-xl-8">
            <div class="col-12">
                <div class="card card-flush h-md-100">
                    <!--begin::Header-->
                    <div class="card-header  border-0 pt-6">
                        <!--begin::Title-->
                        <h3 class="card-title align-users-start flex-column">
                            <span class="card-label fw-bold text-gray-800">Data User</span>
                        </h3>
                        <!--end::Title-->
                    </div>
                    <!--end::Header-->
                    <!--begin::Body-->
                    <div class="card-body pt-6">
                        <!--begin::Table container-->
                        <div class="table-responsive">
                            <!--begin::Table-->
                            <table class="table table-row-dashed align-middle gs-0 gy-3 my-0" id="datatable">
                                <!--begin::Table head-->
                                <thead>
                                    <tr class="text-start text-muted fw-bold fs-7 text-uppercase gs-0">
                                        <th>#</th>
                                        <th>Nama</th>
                                        <th>Email</th>
                                        <th>Terdaftar Pada</th>
                                        <th class="text-center">Jumlah Diagnosa</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <!--end::Table head-->
                                <!--begin::Table body-->
                                <tbody class="text-black-300 fw-semibold">
                                    @foreach ($data as $user)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $user->name }}</td>
                                            <td>{{ $user->email }}</td>
                                            <td>{{ $user->created_at->translatedFormat('l, d M Y H:i') }}</td>
                                            <td class="text-center">{{ $user->diagnosa_count }}</td>
                                            <td class="text-end">
                                                <a href="{{ route('admin.users.show', $user) }}"
                                                    class="btn btn-sm btn-success">
                                                    <i class="fa fa-eye"></i>
                                                </a>

                                                <a href="#" data-id="{{ $user->id }}"
                                                    class="btn btn-sm btn-danger delete-btn">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                                <!--end::Table body-->
                            </table>
                        </div>
                        <!--end::Table-->
                    </div>
                    <!--end: Card Body-->
                </div>
            </div>
        </div>
        <!--end::Row-->
    </div>
@endsection

@section('custom_html')
    <form action="#" method="post" id="delete-form">
        @csrf
        @method('DELETE')
    </form>
@endsection

@push('custom_js')
    <script>
        let deleteBtns = document.querySelectorAll('.delete-btn');

        deleteBtns.forEach((btn) => {
            let id = btn.getAttribute('data-id');

            btn.addEventListener('click', function() {
                Swal.fire({
                    title: 'Hapus Data?',
                    text: "Yakin ingin menghapus data user? Data lain yang terkait juga akan dihapus. Tindakan ini tidak dapat dibatalkan.",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                    confirmButtonText: 'Hapus',
                }).then((result) => {
                    if (result.isConfirmed) {
                        let form = document.querySelector('#delete-form');

                        form.setAttribute(`action`,
                            `{{ route('admin.users.destroy', false) }}/${id}`);
                        form.submit();
                    }
                })
            });
        });
    </script>
@endpush

resources/views/admin/users/show.blade.php
@extends('layouts.metronic')
@section('title', $user->name)

@section('breadcrumb')
    <div class="toolbar py-5 pb-lg-15" id="kt_toolbar">
        <!--begin::Container-->
        <div id="kt_toolbar_container" class=" container-xxl  d-flex flex-stack flex-wrap">
            <!--begin::Page title-->
            <div class="page-title d-flex flex-column me-3">
                <!--begin::Title-->
                <h1 class="d-flex text-white fw-bold my-1 fs-3">
                    Data User
                </h1>
                <!--end::Title-->
                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-1">
                    <!--begin::Item-->
                    <li class="breadcrumb-item text-white opacity-75">
                        <a href="{{ route('admin.dashboard') }}" class="text-white text-hover-primary">
                            Dashboard </a>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li class="breadcrumb-item">
                        <span class="bullet bg-white opacity-75 w-5px h-2px"></span>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li class="breadcrumb-item text-white opacity-75">
                        <a href="{{ route('admin.users.index') }}" class="text-white text-hover-primary">
                            User </a>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li class="breadcrumb-item">
                        <span class="bullet bg-white opacity-75 w-5px h-2px"></span>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li class="breadcrumb-item text-white opacity-75">
                        {{ $user->name }}
                    </li>
                    <!--end::Item-->
                </ul>
                <!--end::Breadcrumb-->
            </div>
            <!--end::Page title-->
            <!--begin::Actions-->
            <div class="d-flex align-items-center py-3 py-md-1">
                <!--begin::Button-->
                <a href="{{ route('admin.users.index') }}" data-bs-theme="light"
                    class="btn bg-body btn-active-color-primary">
                    Kembali </a>
                <!--end::Button-->
            </div>
            <!--end::Actions-->
        </div>
        <!--end::Container-->
    </div>
@endsection

@section('content')
    <div class="content flex-row-fluid" id="kt_content">
        <!--begin::Row-->
        <div class="row g-5 g-xl-8">
            <div class="card card-flush pt-3 mb-5">
                <!--begin::Card header-->
                <div class="card-header">
                    <!--begin::Card title-->
                    <div class="card-title">
                        <h2 class="fw-bold">Data User</h2>
                    </div>
                    <!--begin::Card title-->
                </div>
                <!--end::Card header-->

                <!--begin::Card body-->
                <div class="card-body pt-0">
                    <!--begin::Table wrapper-->
                    <div class="table-responsive">
                        <!--begin::Table-->
                        <div class="table-responsive">
                            <table class="table align-middle table-row-dashed fs-6 fw-semibold gy-4 dataTable no-footer">
                                <tbody>
                                    <tr class="even">
                                        <td class="text-gray-600">Nama</td>
                                        <td class="text-black-600">{{ $user->name }}</td>
                                    </tr>
                                    <tr class="odd">
                                        <td class="text-gray-600">Email</td>
                                        <td class="text-black-600">{{ $user->email }}</td>
                                    </tr>
                                    <tr class="even">
                                        <td class="text-gray-600">Terdaftar Pada</td>
                                        <td class="text-black-600">{{ $user->created_at->translatedFormat('l, d M Y H:i') }}
                                        </td>
                                    </tr>
                                    <tr class="odd">
                                        <td class="text-gray-600">Jumlah Diagnosa</td>
                                        <td class="text-black-600">{{ $user->diagnosa_count }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <!--end::Table-->
                    </div>
                    <!--end::Table wrapper-->
                </div>
                <!--end::Card body-->

                <!--begin::Card footer-->
                <div class="card-footer">
                    <div class="d-flex justify-content-end">
                        <button class="btn btn-danger btn-sm btn-delete ms-2">
                            <i class="bi bi-trash"></i>
                            Hapus
                        </button>
                    </div>
                </div>
                <!--end::Card footer-->
            </div>

            <div class="card card-flush h-md-100">
                <!--begin::Header-->
                <div class="card-header  border-0 pt-6">
                    <!--begin::Title-->
                    <h3 class="card-title align-items-start flex-column">
                        <span class="card-label fw-bold text-gray-800">Data Diagnosa</span>
                    </h3>
                    <!--end::Title-->
                </div>
                <!--end::Header-->
                <!--begin::Body-->
                <div class="card-body pt-6">
                    <!--begin::Table container-->
                    <div class="table-responsive">
                        <!--begin::Table-->
                        <table class="table table-row-dashed align-middle gs-0 gy-3 my-0">
                            <!--begin::Table head-->
                            <thead>
                                <tr class="text-start text-muted fw-bold fs-7 text-uppercase gs-0">
                                    <th>#</th>
                                    <th>Tanggal</th>
                                    <th>Hasil Penyakit</th>
                                    <th>Persentase</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <!--end::Table head-->
                            <!--begin::Table body-->
                            <tbody class="text-black-300 fw-semibold">
                                @forelse ($user->diagnosa as $diagnosa)
                                    <tr class="{{ $loop->iteration % 2 == 0 ? 'odd' : 'even' }}">
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $diagnosa->created_at->translatedFormat('l, d M Y H:i') }}</td>
                                        <td>{{ $diagnosa->penyakit->nama }}</td>
                                        <td>{{ $diagnosa->persentase }}</td>
                                        <td class="text-end">
                                            <a href="{{ route('admin.diagnosa.show', $diagnosa) }}" class="btn btn-sm btn-success">
                                                <i class="fa fa-eye"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="5" class="text-center">Tidak ada data</td>
                                    </tr>
                                @endforelse
                            </tbody>
                            <!--end::Table body-->
                        </table>
                    </div>
                    <!--end::Table-->
                </div>
                <!--end: Card Body-->
            </div>
        </div>
        <!--end::Row-->
    </div>
@endsection

@section('custom_html')
    <form action="{{ route('admin.users.destroy', $user) }}" method="post" id="delete-form">
        @csrf
        @method('DELETE')
    </form>
@endsection

@push('custom_js')
    <script>
        let btnDelete = document.querySelector('.btn-delete');

        btnDelete.addEventListener('click', function(e) {
            e.preventDefault();

            Swal.fire({
                title: 'Hapus Data?',
                text: "Yakin ingin menghapus data user? Data lain yang terkait juga akan dihapus. Tindakan ini tidak dapat dibatalkan.",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Hapus',
            }).then((result) => {
                if (result.isConfirmed) {
                    let deleteForm = document.querySelector('#delete-form');

                    deleteForm.submit();
                }
            })
        });
    </script>
@endpush